# Name of workflow
name: Deploy to Netlify

# When workflow is triggered
on:
  push:
    branches: [main, dev]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Jobs to carry out
jobs:
  build-test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps in job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # Install NodeJS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test

      - name: Build
        run: npm run build --if-present

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production
          path: ./build
          retention-days: 2 # customize artifact retention period. default: 90 days

      # Create and publish a Docker image to GitHub Packages
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  github-pages-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    # look at the ref and only run this job if the branch that triggered the workflow is "dev"
    if: endswith(github.ref, 'dev')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production
          path: ./build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

  netlify-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    # look at the ref and only run this job if the branch that triggered the workflow is main
    if: endswith(github.ref, 'main')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production
          path: ./build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod